<?php
/**
<<<<<<< HEAD
 * Copyright 2017 Adobe
 * All Rights Reserved.
=======
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
>>>>>>> cd2dc8bb627573641d87e5e03a85271f17f3264f
 */
namespace Magento\TestFramework\Utility;

use Magento\Catalog\Model\Indexer\Product\Flat\Table\BuilderInterfaceFactory;
use Magento\TestFramework\UtilityBarFactory;
use Magento\TestFramework\Utility\PartialNamespace\BarFactory as PartialNamespaceBarFactory;
use Magento\Framework\UrlFactory;
use Magento\Catalog\Model\Product\OptionFactory;
use Magento\Catalog\Api\Data\ProductLinkInterfaceFactory;
<<<<<<< HEAD
use PHPUnit\Framework\Attributes\DataProvider;
=======
>>>>>>> cd2dc8bb627573641d87e5e03a85271f17f3264f

class AutogeneratedClassNotInConstructorFinderTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @param string $fileContent
     * @param string[] $expected
<<<<<<< HEAD
     */
    #[DataProvider('getNameWithNamespaceDataProvider')]
=======
     * @dataProvider getNameWithNamespaceDataProvider
     */
>>>>>>> cd2dc8bb627573641d87e5e03a85271f17f3264f
    public function testGetNameWithNamespace($fileContent, $expected)
    {
        require_once __DIR__ . '/Foo.php';

        $classNameExtractor = new ClassNameExtractor();
        $instantiatedByObjectManagerClassExtractor = new AutogeneratedClassNotInConstructorFinder(
            $classNameExtractor
        );
        $this->assertEquals(
            $expected,
            $instantiatedByObjectManagerClassExtractor->find($fileContent)
        );
    }

    /**
     * @return array
     */
<<<<<<< HEAD
    public static function getNameWithNamespaceDataProvider()
=======
    public function getNameWithNamespaceDataProvider()
>>>>>>> cd2dc8bb627573641d87e5e03a85271f17f3264f
    {
        return [
            [
                file_get_contents(__DIR__ . '/Foo.php'),
                [
                    BuilderInterfaceFactory::class,
                    BarFactory::class,
                    PartialNamespaceBarFactory::class,
                    UrlFactory::class,
                    OptionFactory::class,
                    ProductLinkInterfaceFactory::class
                ]
            ]
        ];
    }
}
