define(['jquery'], function ($) {
    'use strict';
    return function () {
        var $app = $('#pv41-app'), $nav = $('#pv41-main-nav'), $underline = $('#pv41-nav-underline');
        if (!$app.length) return;
        var products = [];
        try { products = JSON.parse($('#pv41-products-data').text()); } catch (e) { products = []; }
        var state = { activeTab: $app.data('active-tab') || 'GPU', category: $app.data('category') || 'All', search: $app.data('search') || '', minPrice: parseFloat($app.data('min-price')) || 0, maxPrice: parseFloat($app.data('max-price')) || 999999, availability: $app.data('availability') || 'All', sort: $app.data('sort') || 'Price: High to Low', selectedId: products.length ? products[0].id : null, isPaying: false };
        function normalize(v){ return String(v||'').toLowerCase().trim(); }
        function categoryMatch(product, category){ if(category==='All') return true; var t=normalize(category); if(normalize(product.category_label)===t) return true; if((product.categories||[]).some(function(cat){ return normalize(cat).indexOf(t)!==-1; })) return true; return normalize(product.name).indexOf(t)!==-1; }
        function matches(product){ var searchOk=!state.search || normalize(product.name).indexOf(normalize(state.search))!==-1; var price=parseFloat(product.price||0); var minOk=state.minPrice==='' || price>=parseFloat(state.minPrice||0); var maxOk=state.maxPrice==='' || price<=parseFloat(state.maxPrice||9999999); var availabilityOk=state.availability==='All' || product.availability===state.availability; return searchOk && minOk && maxOk && availabilityOk && categoryMatch(product,state.category); }
        function sortProducts(list){ var copy=list.slice(); switch(state.sort){ case 'Price: Low to High': copy.sort(function(a,b){return a.price-b.price;}); break; case 'Name: A to Z': copy.sort(function(a,b){return String(a.name).localeCompare(String(b.name));}); break; case 'Newest': copy.sort(function(a,b){return (b.id||0)-(a.id||0);}); break; default: copy.sort(function(a,b){return b.price-a.price;}); } return copy; }
        function getFilteredProducts(){ return sortProducts(products.filter(matches)); }
        function currentProduct(){ var filtered=getFilteredProducts(); var product=filtered.find(function(item){ return item.id===state.selectedId; }); if(!product && filtered.length){ product=filtered[0]; state.selectedId=product.id; } return product||null; }
        function setUnderline(){ var $active=$nav.find('.pv41-nav__item.is-active'); if(!$active.length) return; $underline.css({transform:'translateX(' + $active.position().left + 'px)', width:$active.outerWidth() + 'px'}); }
        function stockPillClass(product){ if(!product) return 'pv41-stock-pill pv41-stock-pill--out'; if(product.availability==='Low stock') return 'pv41-stock-pill pv41-stock-pill--low'; if(product.availability==='Out of stock') return 'pv41-stock-pill pv41-stock-pill--out'; return 'pv41-stock-pill pv41-stock-pill--ok'; }
        function updateStats(filtered){ var inStock=0, lowStock=0; filtered.forEach(function(p){ if(p.availability==='In stock') inStock++; if(p.availability==='Low stock') lowStock++; }); $('#pv41-showing-count').text(filtered.length); $('#pv41-in-stock').text(inStock); $('#pv41-low-stock').text(lowStock); $('#pv41-range').text('$' + Number(state.maxPrice||0).toLocaleString(undefined,{minimumFractionDigits:2, maximumFractionDigits:2})); }
        function updateProductView(){ var filtered=getFilteredProducts(); updateStats(filtered); var product=currentProduct(); if(!product){ $('#pv41-card-title').text('No products found'); $('#pv41-card-price').text('$0.00'); $('#pv41-detail-title').text('No products found'); $('#pv41-detail-desc').text('Try adjusting your filters to see available products.'); return; } $('#pv41-card-image').attr('src',product.image).attr('alt',product.name); $('#pv41-card-category').text(product.category_label||'General'); $('#pv41-card-brand').text(product.brand||'MIXIII'); $('#pv41-card-title').text(product.name); $('#pv41-card-price').text(product.price_formatted); $('#pv41-card-stock').text(product.qty); $('#pv41-stock-pill').attr('class',stockPillClass(product)).html((product.availability==='In stock' ? 'In stock: ' : product.availability + ': ') + '<strong id="pv41-card-stock">' + product.qty + '</strong>'); $('#pv41-detail-title').text(product.name); $('#pv41-detail-desc').text(product.description||'No additional description yet.'); $('#pv41-detail-sku').text(product.sku||'-'); $('#pv41-detail-availability').text(product.availability); $('#pv41-detail-category').text(product.category_label||'General'); $('#pv41-detail-price').text(product.price_formatted); $('#pv41-detail-url').attr('href',product.url||'#'); $('#pv41-add-product').val(product.id||0); $('#pv41-add-form').attr('action',product.add_url||'#'); if(product.can_add){ $('#pv41-add-cart').prop('disabled',false).find('.label').text('Add to Cart'); } else { $('#pv41-add-cart').prop('disabled',true).find('.label').text('Choose Options'); } $('.pv41-recent-card').removeClass('is-selected'); $('.pv41-recent-card[data-product-id="' + product.id + '"]').addClass('is-selected'); }
        function bindNav(){ $nav.on('click','.pv41-nav__item',function(){ var $item=$(this); state.activeTab=$item.data('tab'); state.category=state.activeTab==='Deals' ? 'Deals' : state.activeTab; $('#pv41-category').val(state.category); $nav.find('.pv41-nav__item').removeClass('is-active'); $item.addClass('is-active'); setUnderline(); updateProductView(); }); setUnderline(); $(window).on('resize',setUnderline); }
        function bindFilters(){ $('#pv41-header-search').on('input',function(){ state.search=this.value; $('#pv41-search').val(this.value); updateProductView(); }); $('#pv41-search').on('input',function(){ state.search=this.value; $('#pv41-header-search').val(this.value); updateProductView(); }); $('#pv41-category').on('change',function(){ state.category=this.value; updateProductView(); }); $('#pv41-min-price').on('input',function(){ state.minPrice=this.value==='' ? '' : parseFloat(this.value); updateProductView(); }); $('#pv41-max-price').on('input',function(){ state.maxPrice=this.value==='' ? '' : parseFloat(this.value); updateProductView(); }); $('#pv41-availability').on('change',function(){ state.availability=this.value; updateProductView(); }); $('#pv41-sort').on('change',function(){ state.sort=this.value; updateProductView(); }); $('.pv41-recent-card').on('click',function(){ state.selectedId=parseInt($(this).data('product-id'),10); updateProductView(); }); }
        function bindBuyNow(){ $('#pv41-buy-now').on('click',function(){ var $btn=$(this), product=currentProduct(); if(!product || state.isPaying || product.qty<=0) return; state.isPaying=true; $btn.addClass('is-loading'); window.setTimeout(function(){ product.qty=Math.max(0, parseInt(product.qty,10)-1); if(product.qty<=0) product.availability='Out of stock'; else if(product.qty<=5) product.availability='Low stock'; else product.availability='In stock'; state.isPaying=false; $btn.removeClass('is-loading'); updateProductView(); },2000); }); }
        bindNav(); bindFilters(); bindBuyNow(); updateProductView();
    };
});
