<?php
/**
 * Cart checkout actions.
 *
 * @var \Magento\Checkout\Block\Cart $block
 */
?>
<?php if (!$block->hasError()) : ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <div class="pvcart-methods">
        <?php foreach ($methods as $method) : ?>
            <?php $methodHtml = $block->getMethodHtml($method); ?>
            <?php if (trim($methodHtml) !== '') : ?>
                <?= /* @noEscape */ $methodHtml ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
